version: '3'
services:

  ui:
    build: .
    command: ["npm", "run", "dev", ]
    ports:
      - "8080:8080"
    environment:
    - HOST=0.0.0.0
    - PORT=8080
    - NODE_ENV=development
    - DOOM_ENGINE_SERVICE_URL=http://localhost:8081/
    - DOOM_STATE_SERVICE_URL=http://localhost:8082/
    volumes:
    - .:/app
    # bind volume inside container for source mount not shadow image dirs
    - /app/node_modules
    - /app/dist

  doom-engine:
    image: microservice-doom/doom-engine:latest
    environment:
      - DOOM_STATE_SERVICE_URL=http://doom-state:8080/
      - DOOM_STATE_SERVICE_PASSWORD=enginepwd
    ports:
      - "8081:8080"

  doom-state:
    image: microservice-doom/doom-state:latest
    ports:
      - "8082:8080"

 # run production deployment script
  ui-deployment:
    build: .
    command: ["/app/bin/rewrite-config.js"]
    environment:
      - NODE_ENV=production
      - DIST_DIR=/app/dist
      - WWW_DIR=/tmp/www
      - DOOM_ENGINE_SERVICE_URL=http://localhost:8081/
      - DOOM_STATE_SERVICE_URL=http://localhost:8082/
    volumes:
    - .:/app
    # bind volume inside container for source mount not shadow image dirs
    - /app/node_modules
    - /app/dist
    # shared NGINX static files dir
    - www-data:/tmp/www
    depends_on:
      - nginx

  # serve docker image production build with nginx
  nginx:
    image: nginx:1.14
    ports:
      - "8090:80"
    volumes:
    - www-data:/usr/share/nginx/html

volumes:
  www-data:
